#!/usr/bin/bash
iptab=$(iptables -L -vn)
#recieves ip addresses permitted for outbound web connections
ipsarr=$(echo "$iptab" | sed -rn '/^.+tcp spt:443 state ESTABLISHED \/\* isc\.sans\.edu.*$/,/^$/ s/^.+ (([0-9]{1,3}\.){3}[0-9]{1,3}) *(([0-9]{1,3}\.){3}[0-9]{1,3}) *tcp spt:443 state ESTABLISHED .+$/\1/p')
comments=$(echo "$iptab" | sed -rn '/^.+tcp spt:443 state ESTABLISHED \/\* isc\.sans\.edu.*$/,/^$/ s/^.+tcp spt:443 state ESTABLISHED \/\* (.+) .*$/\1/p')
count=0
#convert text to list
ips=()
for i in $ipsarr; do
   ips[$count]=$i
   let "count++"
done
com=()
count=0
for i in $comments; do
   com[$count]=$i 
   let "count++"
done
#deletes firewall rules for outbound web connections
for ((i=0; i<${#ips[@]}; i++)) do
   iptables -D INPUT -d 10.0.0.21 -s ${ips[$i]}  -i eth0 -p tcp -m tcp --sport 80 -m state --state ESTABLISHED -m comment --comment "${com[$i]}" -j ACCEPT
   iptables -D OUTPUT -s 10.0.0.21 -d ${ips[$i]} -o eth0 -p tcp -m tcp --dport 80 -m comment --comment "${com[$i]}" -j ACCEPT
   iptables -D INPUT -d 10.0.0.21 -s ${ips[$i]} -i eth0 -p tcp -m tcp --sport 443 -m state --state ESTABLISHED -m comment --comment "${com[$i]}" -j ACCEPT
   iptables -D OUTPUT -s 10.0.0.21 -d ${ips[$i]} -o eth0 -p tcp -m tcp --dport 443 -m comment --comment "${com[$i]}" -j ACCEPT
done
www4=$(nslookup www4.dshield.org)
isc=$(nslookup isc.sans.edu)
#www4=$(nslookup tesla.com)
#isc=$(nslookup amazon.com)
www4=$(echo "$www4" | sed -rn 's/^Address: (([0-9]{1,3}\.){3}[0-9]{1,3})$/\1/p')
isc=$(echo "$isc" | sed -rn 's/^Address: (([0-9]{1,3}\.){3}[0-9]{1,3})$/\1/p')
declare -A iparry2
count=0
for i in $www4; do
   iparry2["www4.dshield.org""$count"]=$i
   let "count++"
done
for i in $isc; do
   iparry2["isc.sans.edu""$count"]=$i
   let "count++"
done
for i in ${!iparry2[@]};
do
   iptables -I INPUT 15 -d 10.0.0.21 -s ${iparry2[$i]}  -i eth0 -p tcp -m tcp --sport 80 -m state --state ESTABLISHED -m comment --comment "$i" -j ACCEPT
   iptables -I OUTPUT 9 -s 10.0.0.21 -d ${iparry2[$i]} -o eth0 -p tcp -m tcp --dport 80 -m comment --comment "$i" -j ACCEPT
   iptables -I INPUT 15 -d 10.0.0.21 -s ${iparry2[$i]}  -i eth0 -p tcp -m tcp --sport 443 -m state --state ESTABLISHED -m comment --comment "$i" -j ACCEPT
   iptables -I OUTPUT 9 -s 10.0.0.21 -d ${iparry2[$i]} -o eth0 -p tcp -m tcp --dport 443 -m comment --comment "$i" -j ACCEPT
done
